---
  - name: 'windows update'
    hosts: default

    vars:
      - ansible_user: "{{ winrm_user }}"
      - ansible_password: "{{ winrm_password }}"
      - ansible_connection: winrm
      - ansible_winrm_transport: basic
      - ansible_ssh_port: 5985
      - ansible_winrm_server_cert_validation: ignore
    tasks:
      - name: 'Run Updates on Directory Servers then wait 15 mins'
        win_updates:
          category_names:
            - CriticalUpdates
            - SecurityUpdates
          log_path: win_updates.log
          reboot: yes
          reboot_timeout: 900